// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHn083Nj6Q-V2HoGiErUydYfZxe9Z1Q0E',
    appId: '1:391206802141:web:120ef794b7baf612e98134',
    messagingSenderId: '391206802141',
    projectId: 'divipay-8483d',
    authDomain: 'divipay-8483d.firebaseapp.com',
    storageBucket: 'divipay-8483d.firebasestorage.app',
    measurementId: 'G-8PRV2Q6K74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrmbeB-DboDpD7VbGtzpLE07rd4LFXlE',
    appId: '1:391206802141:android:a66e15bec96254a4e98134',
    messagingSenderId: '391206802141',
    projectId: 'divipay-8483d',
    storageBucket: 'divipay-8483d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEOKuCQCaw87694CIqOJXalTfqZ7VzpFE',
    appId: '1:391206802141:ios:99af8eac7d3ce496e98134',
    messagingSenderId: '391206802141',
    projectId: 'divipay-8483d',
    storageBucket: 'divipay-8483d.firebasestorage.app',
    iosBundleId: 'com.example.divipay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUlX1-dKWUJBpdd7n0bLavkmqYY6XQASQ',
    appId: '1:794676786069:ios:b0e2e507a7acd13020bc9c',
    messagingSenderId: '794676786069',
    projectId: 'divipay-559e2',
    storageBucket: 'divipay-559e2.firebasestorage.app',
    iosBundleId: 'com.example.divipay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArOI2atIm0LE3jvZ9CCZg3Cvl8B-9ZfNQ',
    appId: '1:794676786069:web:6aa98be5032e14b520bc9c',
    messagingSenderId: '794676786069',
    projectId: 'divipay-559e2',
    authDomain: 'divipay-559e2.firebaseapp.com',
    storageBucket: 'divipay-559e2.firebasestorage.app',
    measurementId: 'G-JZZ3EH9VCP',
  );
}